### ISSUE TITLE
sh.itjust.works does not allow adult content

### ISSUE THREAD

**Issue by DavidCWGA** [maltfield/awesome-lemmy-instances#19] opened 2023-06-16 01:49 UTC
[sh.itjust.works](https://sh.itjust.works/) is listed as allowing adult content, but it does not:

https://sh.itjust.works/post/22919

**Comment by maltfield** [comment] 2023-06-16 02:00
Please search the existing issues before creating a new one.

This is a duplicate of #16 

Let me know if you have any further questions.

**Closed by maltfield** 2023-06-16 02:00 UTC

**Comment by DavidCWGA** [comment] 2023-06-16 02:04
I _suspect_ that most people will assume, as I did, that NSFW means "all NSFW", not "just some". Ideally the solution to this is to add a new column that shows whether anything is blocked.
