### ISSUE TITLE
VLemmy has been offline -- the list of best instances need to be updated.

### ISSUE THREAD

**Issue by icarofr** [maltfield/awesome-lemmy-instances#33] opened 2023-07-09 20:54 UTC
https://lemmy.sdfeu.org/post/32981 for full context.

**Comment by iopq** [comment] 2023-07-10 07:59
Came here to say the same thing, this needs constant updating, at least in the beginning

**Comment by jheidecker** [comment] 2023-07-11 00:20
Maybe this isn't the best place for join-lemmy.org to link people to if it's not being updated.

**Comment by maltfield** [comment] 2023-07-11 20:45
@jheidecker this repo updates every 1 hour.

Updates have been *temporarily* paused due to an upstream bug with `lemmy-stats-crawler`. The lemmy developers have intentionally decided to break backwards compatibility to nodes that haven't updated to v0.18.0.

That means that any instance admins that haven't yet updated to v0.18.0 will disappear from this list because they can't be discovered by `lemmy-stats-crawler`. I have made an intentional decision to freeze the contents to provide admins time to update due to this breaking change made by the lemmy developers.

**Comment by maltfield** [comment] 2023-07-11 20:46
This is a duplicate of #32

**Closed by maltfield** 2023-07-11 20:46 UTC
