### ISSUE TITLE
VLemmy is down

### ISSUE THREAD

**Issue by Ethab83** [maltfield/awesome-lemmy-instances#34] opened 2023-07-13 03:54 UTC
VLemmy lost its domain name (or something of the like... either way it's down and probably not coming back).

It should probably be removed from the recommended instances.

**Comment by maltfield** [comment] 2023-07-13 15:56
@Ethab83 please search existing issues before posting a new issue on github

Closing as duplicate of #32

**Closed by maltfield** 2023-07-13 15:56 UTC
