### ISSUE TITLE
Issue generating readme file

### ISSUE THREAD

**Issue by subashz** [maltfield/awesome-lemmy-instances#31] opened 2023-07-02 03:01 UTC
/Users/subash/Documents/GitHub/awesome-lemmy-instances
['LICENSE', 'generate_readme.py', 'push.sh', 'README.md', '.gitignore', 'get-uptime.sh', '.github', 'stats-crawler.sh', 'lemmy-stats-crawler', 'awesome-lemmy-instances.csv', '.git', 'lemmy-migration-find-subreddits-communities.jpg']
['Cargo.toml', 'LICENSE', '.woodpecker.yml', 'target', 'Cargo.lock', 'README.md', '.gitignore', 'lemmy-stats-crawler.json', '.git', 'src']
Traceback (most recent call last):
  File "/Users/subash/Documents/GitHub/awesome-lemmy-instances/./generate_readme.py", line 109, in <module>
    instances_with_blocked = [x for x in data['instance_details'] if x['site_info']['federated_instances'] != None ]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/subash/Documents/GitHub/awesome-lemmy-instances/./generate_readme.py", line 109, in <listcomp>
    instances_with_blocked = [x for x in data['instance_details'] if x['site_info']['federated_instances'] != None ]
                                                                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'federated_instances'

**Comment by maltfield** [comment] 2023-07-02 08:14
This is a duplicate of #26

The solution is already available in the `dev` branch if you want to use it. But I haven't merged it to `main` yet because it rejects all lemmy instances <v0.8.0.

Upstream said they won't make it backwards-compatible, so I'm waiting some reasonable amount of time to allow instance admins to upgrade before I merge `dev` with `main`

**Closed by maltfield** 2023-07-02 08:14 UTC
