### ISSUE TITLE
v0.18.0 instances not appearing

### ISSUE THREAD

**Issue by novakeith** [maltfield/awesome-lemmy-instances#26] opened 2023-06-23 21:55 UTC
I haven't looked too closely at it yet, but I'm no longer listed (links.dartboard.social) as well as a few other instances I know did the upgrade today (sh.itjust.works for example).

**Comment by maltfield** [comment] 2023-06-23 22:45
thanks for the report. I've confirmed it and created an issue upstream:

 * https://github.com/LemmyNet/lemmy-stats-crawler/issues/9

**Comment by maltfield** [comment] 2023-06-23 23:42
In the meantime, I've restored an old version of the README before the release of v0.18.0 and paused the hourly cron'd updates.

**Comment by novakeith** [comment] 2023-06-24 02:15
Thanks. Thought I did something to tick the community-at-large off 😅

**Comment by maltfield** [comment] 2023-06-28 19:56
Update: The upstream issue of v0.18.0 instances not appearing has been fixed upstream, but the changes introduced a new bug: Instances with <v0.18.0 that have account registration signups set to `requireapplication` are now absent.

This appears to be due to some case-sensitive change from `requireapplication` to `RequireApplication`

 * https://github.com/LemmyNet/lemmy-stats-crawler/issues/9#issuecomment-1611991067

**Comment by iopq** [comment] 2023-08-01 04:09
> So I'm keeping the stale version up, otherwise the list will remove all instances that [a] haven't yet upgraded to v0.18.0 and [b] have registration set to "requireapplication" will not appear in the table.

You've said you're giving them a few weeks to upgrade. Maybe it's time? Lemmy.world is under maintenance and I don't know what to use

**Comment by maltfield** [comment] 2023-08-04 13:13
The latest build's complete table comparison looks ok, but there's no recommended instances.

It appears that every instance is getting disqualified because they're marked as "Federated" = No. That needs to be fixed.

 * https://github.com/maltfield/awesome-lemmy-instances/blob/543b9bb46e8b38aeb19110159ffd88d663968b18/README.md

**Comment by maltfield** [comment] 2023-08-04 15:21
This is done

 * https://github.com/maltfield/awesome-lemmy-instances/blob/e8ee41a9c0d0fdffddefe7bcf80fcf8c8cc6c778/README.md

**Closed by maltfield** 2023-08-04 15:21 UTC

**Comment by novakeith** [comment] 2023-08-09 20:36
Sorry to comment on a closed issue, but there are only two instances in the table. Are you sure this has been fixed? I know multiple instances that moved to 18.3, if not 18.4 by now.

**Comment by maltfield** [comment] 2023-08-09 21:21
@novakeith keep scrolling down; there's maybe hundreds of instances in the table

 * https://github.com/maltfield/awesome-lemmy-instances#all-lemmy-instances

The "Recommended Instances" list is intentionally short. Part of the hangup that people have on federated instances is the UX that makes it overwhelming for folks choosing an instance. Rather, we choose the best instances that meet our criteria and display the ones with the highest uptime. Currently there's only two that meet our criteria and have 100% uptime.

Either should be fine; we recommend folks just pick one of the two at random. If users want to dig deeper, they can check the "all instances" table below.

**Comment by novakeith** [comment] 2023-08-09 21:31
Ooof my bad! Gave it the quick skim and stopped when I hit the first table. Thanks.
